name: Build and Upload Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: choco install -y rust

      - name: Build press-key-cheater
        run: |
          cargo test
          cargo build --release

      - name: Build show-key
        run: |
          cd ./show-key
          cargo build --release

      - name: prepare artifact
        shell: cmd
        run: |
          ren press-key-cheater.bat.tpl press-key-cheater.bat
          move target\release\press-key-cheater.exe press-key-cheater.exe
          move show-key\target\release\show-key.exe show-key.exe

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: press-key-cheater
          path: |
            press-key-cheater.exe
            show-key.exe
            press-key-cheater.bat
